.github/workflows/assign_project.yml
Closes #3 
Adds the column_name setting, which is required since the "To Do" column that the action defaults to does not exists on our Backlog project.
=> #3 - Add column name to project assigning action

.eslintrc.json, .github/workflows/pull_request.yml, package-lock.json, package.json
This adds a linting configuration and a github action to run the lint check on all PRs.  The configuration was pieced together from various suggested configs I found online.  Some things may not be 100% necessary, but also shouldn't hurt anything.  I'm specifically thinking about the inclusion of the react-hooks stuff, since I don't think we're using hooks right now.  The errors that get reported all seem reasonable, so this config feels like a good starting point.
* See the "Pull Request / lint (14.x) (pull_request)" action that ran under the failed checks in this PR. The fact that the check fails is good here, since this PR is about adding the action to run the linting, not for fixing all of the linting errors.
* If you want to try running eslint yourself, just check out branch …
=> #31 - Add linting github action

src/components/Routes/Routes.tsx, src/containers/AuthContainer.tsx, src/containers/ConfigContainer.tsx, src/hooks/useMyAxios.ts, src/hooks/useSystems.tsx, src/hooks/useToken.ts, src/hooks/useTokenExpiration.ts, src/pages/CommandIndex/CommandIndexTable/data.tsx, src/pages/CommandView/CommandView.tsx, src/pages/GardenAdmin/GardenAdmin.tsx, src/pages/GardenAdminView/GardenAdminView.tsx, src/pages/JobIndex/JobIndex.tsx, src/pages/RequestView/RequestView.tsx, src/pages/RequestsIndex/RequestsIndexTable/data/data.tsx, src/pages/SystemAdmin/SystemAdmin.tsx, src/pages/SystemIndex/SystemIndexTable/data.tsx
Closes #57 
- Switch `authEnabled` and `debugEnabled` in `ServerConfigContainer` to be memoized variables vs functions
- Add missing `getConfig` dependency to the config retrieval in Routes
- Fix the double fetch of the `Request` table's data - Add more useCallbacks and useMemo's for data that shouldn't be changing or doesn't need to be recomputed.
- Update `useToken::setToken()` to save the Request and Response handlers as callbacks, also remove the old interceptors when adding new ones
With appropriate useCallback and useMemo's, the current `axiosInstance`/`useAxios` pattern is sufficient.
=> #57 - Fix effects for config and auth

src/components/PageHeader.tsx, src/components/Table/filters/DateRangeColumnFilter.tsx, src/components/Table/toolbar/ColumnHidePage.tsx, src/components/Table/toolbar/FilterPage.tsx, src/components/UI/Theme/Theme.ts, src/pages/CommandIndex/CommandIndexTable/CommandIndexTable.tsx, src/pages/RequestsIndex/RequestsIndexTable/RequestsIndexTable.tsx, src/pages/SystemIndex/SystemIndexTable/ExploreButton.tsx, src/pages/SystemIndex/SystemIndexTable/data.tsx
Closes #54 
A second attempt at updating the dark and light themes. I have tried to make things less granular, the exceptions to this being in the table (which has its needed changes in CSS baseline) and one spot in a popup menu that may go away during other issues anyways. I changed various buttons and checkboxes in the rest of the code to use the theme palette component I thought was best, and also upped the text font sizes. There are still some things that don't look quite right because the UI will be changing more even after this issue eventually ends, but these are my suggestions for the main color schemes at least.
Feedback appreciated, especially on the light theme.
=> Issue #54 v2: Updated dark and light themes

src/components/Table/SSRTable.tsx, src/components/Table/Table.tsx, src/components/UI/NavigationBar/DrawerFooter.test.tsx, src/hooks/useBlockList.tsx, src/pages/CommandBlocklistView/CommandBlocklistView.test.tsx, src/pages/CommandBlocklistView/CommandBlocklistView.tsx, src/pages/JobView/JobButton.test.tsx, src/pages/JobView/JobView.test.tsx, src/test/testAxiosMock.ts, src/test/testData.ts, src/types/backend-types.ts
Closes #99 
`tableName` is now optional, can use `tableKey` in its place.
Fixes "double heading" in Command Blocklist page and adds tests for that page
=> #99 - add table key, table name is optional

src/pages/CommandView/CommandViewForm.tsx
Closes #119 
Turns out, @rjsf/material-ui is for MUI v4. We are using MUI v5. Thankfully [there is v5 support](https://github.com/rjsf-team/react-jsonschema-form/pull/2605/files#diff-e299216e91090fe3c850b4c1bbed411159d7adfe532772ea69722c14f1d0c419) shipped with @rjsf/material-ui by default. No apparent bugs swapping to MUI v5 Form.
If we ever upgrade to RJSF v5, the MUI v5 support forks off into @rjsf/mui in-order to solve a few bugs. RJSF v4 > v5 is non-trivial though, so just going with the quick fix for now since it was just a small styling problem and nothing seems to have broken.
The symptom was the "bad" buttons had an extra class that was overriding the styling. This [intermittent class injection was an artifact of MUI v4 installed by …
=> #119 - Fix Command View Form button display

src/components/QueueModal.test.tsx, src/components/QueueModal.tsx, src/pages/SystemAdmin/SystemCardInstances.test.tsx, src/test/test-values.ts
Closes #116 
Hides toolbar and pagination on Queue modal on System Admin page
=> #116 - hide Queue Modal table header/footer

package.json
Closes #157 
Configures code coverage for Jest and adds `test-coverage` script to package.json. Made a separate script instead of attaching to main test script as coverage causes tests to take longer to run. Outputs text summary in console and generates HTML report in `/coverage` accessible by opening the index.html file in your browser of choice.
=> #157 - adding coverage script

src/components/UI/NavigationBar/MenuList/LogoutButton.test.tsx, src/components/UI/NavigationBar/MenuList/LogoutButton.tsx, src/components/UI/NavigationBar/MenuList/MenuList.test.tsx, src/components/UI/NavigationBar/MenuList/MenuList.tsx
Closes #64 
This PR adds a logout button that is conditionally rendered only when the user is logged in. The logout button then calls logout() from within the AuthContainer.
* Launch beergarden, with auth enabled in the example configs
* Login as a user
* Open the menu list and see that logout button is added
* Clicking the logout button should log the user out and navigate the user back to the login page
=> Closes #64 - Add logout button

src/components/Table/filters/SelectionColumnFilter.tsx, src/components/Table/filters/numericTextFilter.tsx
Closes #170 
Removes the last references to any except one in a type definition file which is a logical use. Going forward during reviews, remember to not introduce `any` type if it can be avoided.
=> Issue 170 - remove references to any type

config-overrides.js
Closes #171 
Webpack does not watch anything inside `node_modules` or any test files. This means when using the dev server `npm start` those items are ignored and do not cause the server to be restarted. Server will still restart upon module install/uninstall (as that changes the package.json/package-lock.json which are still watched by webpack)
=> issue 171 update webpack watch ignore

package-lock.json, package.json
Closes #115 
This PR fixes the Swagger UI link so that it loads the spec for the beergarden API instead of the petstore. This involved downgrading the swagger version so that ?url= was an allowed parameter
* Open the menu and click Open API Documentation
* You should be navigated to the Swagger UI for Beergarden (api/v1/spec)
=> 115 point open api link

src/components/UI/NavigationBar/NavigationBar.test.tsx, src/components/UI/NavigationBar/NavigationBar.tsx
Closes #156 
Manipulates URL to prevent it looking weird to the user. Checks URL on each page load. Follows these cases:
- `4000/something#/systems` > `4000/#/systems`
- `4000/other/#/systems` > `4000/#/systems`
- `4000/#first/systems` > `4000/#/systems`
- `4000/#first/requests` > `4000/#/requests`
- `4000/#second/` > `4000/#/systems`
- `4000/#/second` > `4000/#/systems`
- `4000/#second/bad` > `4000/#/systems`
=> #156 hash router workaround

src/hooks/useSystems.tsx
Closes #88 
Starting or stopping some or all instances in a system should result in color changes on the UI, such that:
* A system, instance, or namespace with at least 1 instance in STOPPED status is highlighted red
* A system, instance, or namespace with all instances in RUNNING status is highlighted green
* A system that is deleted is removed from the page
Previously, these changes were only rendered upon a user refreshing the page. Now this is done automatically.
To test:
1. Open Admin > Systems in Sidebar menu
2. Start and stop an individual instance in a system to see the change
3. Start and stop all instances in the system to see the change
4. Reload a system to see the change
5. Delete a system to see the change
Ticket for refactoring useSystems hook and adding tests here: #197
=> 88 - Make system admin alerts responsive

src/components/Table/defaults/OverflowCellRenderer.tsx
Closes #222 
I change the color of the text in the table, so it will be white or black based on which theme is actively being used. 
To test the text in the table on the systems page should now be white while in dark mode and should remain black when in light mode.
=> Changed color of Text in Table

src/hooks/useSystems.test.tsx, src/hooks/useSystems.tsx, src/pages/JobCreate/JobCreateSystemsTable/JobCreateSystemsTable.tsx, src/pages/JobCreate/JobCreateSystemsTable/data.tsx, src/pages/JobUpdate/UpdateJobView.tsx, src/pages/SystemAdmin/NamespaceCard.test.tsx, src/pages/SystemAdmin/NamespaceCard.tsx, src/pages/SystemAdmin/SystemAdminCard.tsx, src/pages/SystemIndex/SystemIndex.test.tsx, src/pages/SystemIndex/SystemIndex.tsx, src/pages/SystemIndex/systemIndexHelpers.tsx, src/test/axios-mock.ts
Closes #197 
- Refactored and added tests for the useSystems hook
- Refactored pages that used the old useSystems hook: NamespaceCard, SystemIndex, SystemAdminCard, UpdateJobView, JobCreateSystemsTable
- Added tests for NamespaceCard and SystemIndex
- Snackbar alerts in respective component when useSystems hook fails
=> Refactor useSystems hook to use promises

src/pages/JobView/JobView.test.tsx, src/pages/JobView/JobView.tsx
Closes #218 
Adds modal to have user confirm they want to delete job on single job page (under Scheduler). Minor refactor of permission check on that page to fix it.
=> #218 - Confirm deleting job

src/pages/CommandIndex/CommandIndex.tsx, src/pages/GardenAdminView/GardenAdminView.tsx, src/pages/RequestView/RequestViewTable.tsx
Closes #162 
Adjust table keys to make each use of the tables distinct in the local storage. 
1. From the Systems page, select any of the `Explore` buttons. For example, select the button for "complex".
2. On the resulting Command page, add a filter. For example, add the term `echo` to the command filter.
3. Navigate back to the Systems page and choose a different `Explore` button. For example, choose the button for "deploy". Note that the table on the resulting page does not have the filter applied.
4. Select any of the pages in the breadcrumb navigation. They should also not have the filter applied.
=> #162 - change table keys

src/components/Table/SSRTable.tsx, src/components/Table/Table.tsx, src/components/Table/toolbar/Toolbar.tsx, src/pages/RequestView/RequestViewTable.tsx
Closes #131 
Refactor to reduce the amount of empty whitespace above tables. Applied to both table components.
=> #131 - condense table heading space

src/components/UI/NavigationBar/NavigationBar.test.tsx, src/components/UI/NavigationBar/NavigationBar.tsx
Closes #260 
Removes a check that prevents "bad" base URLs (i.e. `4000:/bad/#/systems` still shows systems page). This check needs to be removed to allow for the "`/preview` hosting" that the production environment uses. The options were to whitelist `preview` specifically or just open up the base portion to anything knowing that there may be cases where extra characters are in the base URL that don't need to be there. Team discussion chose the latter as it allows users to host their production build however they like.
=> #260 - remove url base check

src/components/Table/SSRTable.tsx, src/components/Table/filters/TextFilter.tsx
Closes #245 
Filters were behaving oddly on the Requests page since it sends a call to the backend to actually do the filtering, triggering the entire page to be re-rendered. Removed the debounced auto-apply feature and replaced with lose focus or Enter key to "submit" filter. This applies to all tables for consistency. Added tooltip to remind users to click away or press Enter that disappears after a short window.
=> #245 - change how filters are applied

src/components/Table/toolbar/Toolbar.tsx, src/pages/JobIndex/JobIndex.tsx
Closes #193 
Makes the text-only buttons above the Request Scheduler page table look more like buttons so users know they can click them.
=> #193 - job index buttons look like buttons

src/components/ErrorAlert.test.tsx, src/components/ErrorAlert.tsx, src/hooks/useBlockList.tsx, src/hooks/useCommands.tsx, src/hooks/useCommandsParameterized.tsx, src/hooks/useNamespace.tsx, src/pages/CommandBlocklistView/CommandBlocklistView.tsx, src/pages/CommandIndex/CommandIndex.tsx, src/pages/GardenAdmin/GardenAdmin.tsx, src/pages/GardenAdminView/GardenAdminView.tsx, src/pages/JobCreate/JobCreate.tsx, src/pages/JobCreate/JobCreateSystemsTable.tsx, src/pages/JobIndex/JobIndex.test.tsx, src/pages/JobIndex/JobIndex.tsx, src/pages/JobView/JobView.test.tsx, src/pages/JobView/JobView.tsx, src/pages/RequestView/RequestView.test.tsx, src/pages/RequestView/RequestView.tsx, src/pages/RequestsIndex/RequestsIndex.tsx, src/pages/RequestsIndex/requestsIndexData.tsx, src/pages/SystemAdmin/SystemAdmin.tsx, src/pages/SystemIndex/SystemIndex.test.tsx, src/pages/SystemIndex/SystemIndex.tsx, src/pages/UsersIndex/UsersIndex.tsx, src/pages/UsersView/UsersView.test.tsx, src/pages/UsersView/UsersView.tsx
Closes #147 
I added an alert that will be shown instead of showing components with no data because there was an error to retrieving the data from the back-end. 
The alert should be shown if there was an error with getting the initial data for the page.
On the single garden, single job and single request pages, the alert should be shown with a 404 error when trying to navigate to an identifier that is not in the database.
For all the other pages if the back-end is shutdown the alert should be shown with a 500 error.
=> #147 - Added Alert to show more info with errors

src/components/Routes/Routes.tsx, src/containers/AuthContainer.tsx, src/containers/PermissionsContainer.test.tsx, src/containers/PermissionsContainer.tsx, src/pages/Login/Login.tsx
Closes #202 
Changed how the router routes user after login. 
If you navigate to any route other than `/systems` before logging in you should be routed to the route entered instead of being routed to `/systems`, as long as  you have access to that route. If you do not have access to the route you will be routed to `/systems`
=> #202 - Routes user to url path entered after login

src/components/LogModal.tsx, src/components/UI/Theme/Theme.ts, src/pages/RequestView/RemakeRequestButton/CannotReExecuteButton.tsx, src/pages/RequestView/RemakeRequestButton/RemakeRequestButton.tsx
Closes #306 
Could not reproduce the issue with button becoming disabled on JSON card close without turning on the linter, so nothing to fix there.
Color for disabled buttons slightly adjusted in dark mode. Had to specifically apply to the `Remake Request` button as it was not applying automatically for some reason.
=> #306 - tweak disabled buttons in dark mode

src/components/Table/Table.test.tsx, src/components/Table/Table.tsx
Closes #319 
Adds check in table to not render filter row if there are no columns that are filterable
=> #319 - disable filter row if no filters enabled

src/components/Table/defaults/DefaultGlobalFilter.tsx, src/pages/JobCreate/JobCreate.tsx, src/pages/JobIndex/JobIndex.tsx, src/pages/RequestsIndex/RequestsIndex.tsx
Closes #303 
Change the table header buttons to have consistent styling as the table header buttons found on the jobs table.
=> #303 changed table header buttons to consistent styling

src/containers/PermissionsContainer.tsx
Closes #323 
Changed `myObject.hasOwnProperty(somePropertyName)` to `Object.prototype.hasOwnProperty.call(myObject, somePropertyName)` so `eslint-disable-next-line no-prototype-builtins` is no longer needed and has been removed.
=> 323 removed unnecessary eslint disable

src/containers/PermissionsContainer.tsx, src/pages/CommandIndex/CommandIndex.tsx, src/pages/CommandIndex/ExecuteButton.tsx, src/pages/CommandIndex/commandIndexHelpers.tsx, src/pages/RequestView/RequestView.test.tsx, src/pages/RequestView/RequestView.tsx, src/utils/commandFormatters.tsx
Closes #375 
Command Index table no longer hides button column if there are no permissions. If you are on a namespace only level, a permission check inaccurately comes back as false and the column is hid. If the permission is checked on a per-button basis, the check is accurate.
=> #375 - missing execute button fix

src/components/Routes/Routes.test.tsx, src/components/UI/NavigationBar/MenuList/AdminMenu.test.tsx, src/components/UI/NavigationBar/MenuList/LogoutButton.test.tsx, src/components/UI/NavigationBar/MenuList/MenuList.test.tsx, src/components/UI/NavigationBar/NavigationBar.test.tsx, src/containers/PermissionsContainer.test.tsx, src/pages/CommandIndex/CommandIndex.test.tsx, src/pages/CommandIndex/ExecuteButton.test.tsx, src/pages/CommandView/CommandView.test.tsx, src/pages/GardenAdmin/GardenAdminCard.test.tsx, src/pages/JobIndex/JobIndex.test.tsx, src/pages/JobView/JobView.test.tsx, src/pages/RequestsIndex/requestsIndexData.tsx, src/pages/SystemAdmin/NamespaceCard.test.tsx, src/pages/UsersIndex/UsersIndex.test.tsx, src/test/axios-mock.ts, src/test/testMocks.tsx
Closes #363 
Fixes all the problems with the unit tests so none are skipped and all are passing
There are some error logs that occur during the tests. They should be the message `data.tsx:handleRefresh() - error from execute: Cancel { message: undefined }` which is "intentionally" logged by the UI on the requests page.
=> #363 - fix unit tests

src/pages/CommandView/CommandView.tsx
Closes #407 
Made changes to get systems and find the system and command, when system and command are undefined on the command view page, so the page can be navigated to by url and refreshed.
=> #407 Navigate to command by url

src/components/LabeledData.test.tsx, src/components/LabeledData.tsx, src/pages/GardenAdmin/GardenAdmin.tsx, src/pages/GardenAdmin/GardenAdminCard.tsx, src/pages/GardenAdminView/GardenAdminInfoCard.tsx
Closes #401 
Reworked how the garden admin pages does spacing around `LabeledData` so the alert no longer gets a horizontal scroll bar when the garden status is `NOT_CONFIGURED`.
=> #401 Garden status scrolls rather than expanding

src/pages/GardenAdminView/GardenAdminView.tsx, src/pages/SystemIndex/systemIndexHelpers.tsx
Closes #399 
The garden not editable alert is moved to the top of the page to make it easier to see when viewing the local garden.
=> Garden not editable alert moved 

src/components/FormComponents/FormTextField.tsx, src/pages/CommandView/CommandJobForm.tsx, src/pages/CommandView/ParameterElements/ParamTextField.tsx
Closes #425
Added a `Tooltip` with an `Alert` or `CircularProgress` to the field label to indicate when a dependent field needs selected, if there was an error loading the choices or the choices are currently being loaded.
I found an issue with self referring dynamic commands where setting `registerOptions.setValueAs` caused a render loop and had to delete `registerOptions.setValueAs` so self referring dynamic commands would work again.
=> 425 Add dynamic command status indicator
